-- Seed data for incident_cases
-- Requirements: 5.1, 5.2, 8.1

BEGIN;

DO $$
DECLARE
    v_tenant_id UUID;
    v_dubai_site_id UUID;
    v_jebel_site_id UUID;
    v_aweer_site_id UUID;
    v_mohammed_user_id UUID;
    v_sarah_user_id UUID;
    v_fatima_user_id UUID;
    v_omar_user_id UUID;
    v_counter INT;
BEGIN
    -- Get tenant
    SELECT id INTO v_tenant_id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1;
    
    IF v_tenant_id IS NULL THEN
        RAISE NOTICE 'Tenant "DEWA - Transmission" not found. Skipping seeding.';
        RETURN;
    END IF;
    
    -- Get sites
    SELECT id INTO v_dubai_site_id FROM sites WHERE name = 'Dubai Main Substation' AND tenant_id = v_tenant_id;
    SELECT id INTO v_jebel_site_id FROM sites WHERE name = 'Jebel Ali Grid Station' AND tenant_id = v_tenant_id;
    SELECT id INTO v_aweer_site_id FROM sites WHERE name = 'Al Aweer Regional Hub' AND tenant_id = v_tenant_id;
    
    -- Get users
    SELECT id INTO v_mohammed_user_id FROM security_users WHERE username = 'mohammed.binrashid' AND tenant_id = v_tenant_id;
    SELECT id INTO v_sarah_user_id FROM security_users WHERE username = 'sarah.alnuaimi' AND tenant_id = v_tenant_id;
    SELECT id INTO v_fatima_user_id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = v_tenant_id;
    SELECT id INTO v_omar_user_id FROM security_users WHERE username = 'omar.alfalasi' AND tenant_id = v_tenant_id;

    -- Clear existing incident cases for this tenant
    DELETE FROM incident_cases WHERE tenant_id = v_tenant_id;

    -- Insert Incident Cases
    INSERT INTO incident_cases (
        tenant_id, title, description, incident_type, severity, status, priority,
        assigned_to, incident_commander, affected_sites, affected_assets,
        business_impact, estimated_cost, containment_actions, eradication_actions, recovery_actions, lessons_learned,
        detected_at, reported_at
    ) VALUES
    -- Critical Active Incidents
    (
        v_tenant_id,
        'Active Malware Infection - Jebel Ali',
        'Unauthorized malware detected on HMI workstations at Jebel Ali Grid Station targeting SCADA protocols.',
        'malware-infection',
        'critical',
        'investigating',
        'p1-critical',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        'High potential for operational disruption and unauthorized grid control.',
        150000.00,
        ARRAY['Isolate affected workstations', 'Block command and control IP addresses'],
        ARRAY['Run full antivirus scan', 'Reimage infected workstations from known-good backups'],
        ARRAY['Restore system operations', 'Verify integrity of SCADA configurations'],
        'Initial assessment suggests entry via infected USB drive during maintenance.',
        NOW() - INTERVAL '4 hours',
        NOW() - INTERVAL '3 hours'
    ),
    (
        v_tenant_id,
        'Ransomware Attack - Corporate Network',
        'Ransomware detected encrypting files on corporate network with potential OT network spread.',
        'malware-infection',
        'critical',
        'contained',
        'p1-critical',
        v_sarah_user_id,
        v_mohammed_user_id,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        'Critical threat to business operations and data integrity. OT network isolated as precaution.',
        500000.00,
        ARRAY['Isolated corporate network from OT', 'Disabled all VPN connections', 'Shut down email servers'],
        ARRAY['Identify patient zero', 'Remove ransomware using decryption tools', 'Restore from backups'],
        NULL,
        'Rapid containment prevented spread to OT networks. Email phishing vector identified.',
        NOW() - INTERVAL '8 hours',
        NOW() - INTERVAL '7 hours'
    ),
    (
        v_tenant_id,
        'Power Grid Oscillation Anomaly',
        'Unexplained power oscillations detected across multiple transmission sites suggesting potential synchronized manipulation.',
        'system-compromise',
        'high',
        'open',
        'p2-high',
        NULL,
        v_mohammed_user_id,
        ARRAY[v_jebel_site_id, v_dubai_site_id],
        ARRAY[]::UUID[],
        'Critical threat to grid stability and equipment lifespan.',
        120000.00,
        ARRAY['Enable high-speed telemetry recording', 'Increase sampling frequency on protection relays'],
        NULL,
        NULL,
        'Investigation ongoing into potential wide-area network compromise.',
        NOW() - INTERVAL '2 hours',
        NOW() - INTERVAL '1 hour'
    ),
    
    -- High Priority Incidents
    (
        v_tenant_id,
        'Unauthorized Access Attempt - Dubai Main',
        'Multiple failed login attempts detected on the main gateway from a suspicious external IP address.',
        'unauthorized-access',
        'high',
        'contained',
        'p2-high',
        v_sarah_user_id,
        v_mohammed_user_id,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        'Potential for unauthorized access to the internal network and sensitive grid data.',
        50000.00,
        ARRAY['Block malicious IP address at firewall', 'Reset credentials for targeted accounts'],
        ARRAY['Audit logs for successful logins from suspicious IP', 'Verify two-factor authentication configuration'],
        ARRAY['Monitor for further access attempts', 'Implement geo-fencing for administrative access'],
        'Successful containment within 30 minutes of detection.',
        NOW() - INTERVAL '1 day',
        NOW() - INTERVAL '23 hours'
    ),
    (
        v_tenant_id,
        'Network Intrusion Attempt',
        'Multiple failed network intrusion attempts detected across transmission network infrastructure.',
        'unauthorized-access',
        'high',
        'open',
        'p2-high',
        v_omar_user_id,
        v_fatima_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id],
        ARRAY[]::UUID[],
        'Medium - Network security at risk',
        50000.00,
        ARRAY['Strengthened firewall rules', 'Implemented additional monitoring'],
        NULL,
        NULL,
        'Ongoing monitoring for suspicious network activity.',
        NOW() - INTERVAL '3 days',
        NOW() - INTERVAL '2 days 23 hours'
    ),
    (
        v_tenant_id,
        'DDoS Attack on SCADA Communication',
        'Distributed denial of service attack targeting SCADA communication gateway causing intermittent connectivity loss.',
        'denial-of-service',
        'high',
        'investigating',
        'p2-high',
        v_omar_user_id,
        v_sarah_user_id,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        'Communication disruption affecting remote monitoring and control capabilities.',
        80000.00,
        ARRAY['Enabled DDoS mitigation at ISP level', 'Activated backup communication paths'],
        ARRAY['Identify attack source', 'Blacklist attacking IP ranges'],
        NULL,
        NULL,
        NOW() - INTERVAL '6 hours',
        NOW() - INTERVAL '5 hours'
    ),
    (
        v_tenant_id,
        'Suspicious Data Exfiltration Activity',
        'Large volume of data transfer detected from engineering workstation to unknown external server.',
        'data-exfiltration',
        'high',
        'investigating',
        'p2-high',
        v_fatima_user_id,
        v_omar_user_id,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        'Potential intellectual property theft and exposure of critical infrastructure designs.',
        200000.00,
        ARRAY['Isolated affected workstation', 'Blocked destination IP at firewall', 'Revoked user credentials'],
        NULL,
        NULL,
        NULL,
        NOW() - INTERVAL '12 hours',
        NOW() - INTERVAL '11 hours'
    ),
    (
        v_tenant_id,
        'Insider Threat - Unauthorized Configuration Changes',
        'Unauthorized modifications to protection relay settings detected during off-hours by terminated employee credentials.',
        'insider-threat',
        'high',
        'contained',
        'p2-high',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        'High risk of protection system malfunction and potential equipment damage.',
        90000.00,
        ARRAY['Disabled compromised credentials', 'Reverted unauthorized changes', 'Enabled change approval workflow'],
        ARRAY['Review all recent configuration changes', 'Audit user access logs'],
        ARRAY['Implement mandatory change review', 'Enhanced monitoring of privileged actions'],
        'Access management process needs immediate improvement for offboarding.',
        NOW() - INTERVAL '18 hours',
        NOW() - INTERVAL '17 hours'
    ),

    -- Medium Priority Incidents
    (
        v_tenant_id,
        'Unauthorized Physical Access',
        'Security breach detected at Al Aweer Regional Hub. Unauthorized personnel gained access to control room.',
        'physical-security',
        'medium',
        'resolved',
        'p3-medium',
        v_fatima_user_id,
        v_omar_user_id,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        'Low - No system compromise detected',
        15000.00,
        ARRAY['Enhanced physical security measures', 'Reviewed access logs', 'Updated badge access controls'],
        NULL,
        NULL,
        'Physical security protocols need regular review and testing',
        NOW() - INTERVAL '2 days',
        NOW() - INTERVAL '47 hours'
    ),
    (
        v_tenant_id,
        'Phishing Email Campaign Targeting Engineers',
        'Widespread phishing campaign detected targeting SCADA engineers with malicious attachments.',
        'unauthorized-access',
        'medium',
        'contained',
        'p3-medium',
        v_sarah_user_id,
        v_fatima_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Medium - Risk of credential theft and malware infection.',
        25000.00,
        ARRAY['Blocked sender domain', 'Quarantined all emails', 'Sent security awareness alert'],
        ARRAY['Scan all endpoints for malware', 'Force password resets for targeted users'],
        ARRAY['Enhanced email filtering', 'Mandatory security training'],
        '3 users opened attachments but no malware execution detected.',
        NOW() - INTERVAL '4 days',
        NOW() - INTERVAL '3 days 22 hours'
    ),
    (
        v_tenant_id,
        'Weak Password Policy Violation',
        'Automated scan detected multiple user accounts with weak passwords not meeting policy requirements.',
        'unauthorized-access',
        'medium',
        'resolved',
        'p3-medium',
        v_omar_user_id,
        v_fatima_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Potential for brute force attacks and unauthorized access.',
        10000.00,
        ARRAY['Forced password resets for affected accounts', 'Enabled password complexity enforcement'],
        NULL,
        NULL,
        'Password policy enforcement needs automation at directory level.',
        NOW() - INTERVAL '5 days',
        NOW() - INTERVAL '5 days'
    ),
    (
        v_tenant_id,
        'Firmware Vulnerability - Protection Relays',
        'Critical firmware vulnerability discovered in Siemens SIPROTEC relays allowing remote code execution.',
        'system-compromise',
        'medium',
        'open',
        'p3-medium',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        'High risk if exploited but no active exploitation detected.',
        75000.00,
        ARRAY['Isolated vulnerable devices from external access', 'Implemented additional monitoring'],
        ARRAY['Apply firmware patches during next maintenance window'],
        NULL,
        NULL,
        NOW() - INTERVAL '7 days',
        NOW() - INTERVAL '7 days'
    ),
    (
        v_tenant_id,
        'USB Drive Malware Detection',
        'Malware detected on USB drive used by maintenance contractor at Dubai Main Substation.',
        'malware-infection',
        'medium',
        'resolved',
        'p3-medium',
        v_sarah_user_id,
        v_omar_user_id,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        'Low - Malware detected before execution.',
        5000.00,
        ARRAY['Confiscated USB drive', 'Scanned all contractor equipment'],
        ARRAY['Updated antivirus definitions', 'Rescanned all endpoints'],
        ARRAY['Implemented USB device control policy', 'Contractor security training'],
        'USB control policy needs enforcement through technical controls.',
        NOW() - INTERVAL '10 days',
        NOW() - INTERVAL '10 days'
    ),

    -- Historical Resolved/Closed Incidents
    (
        v_tenant_id,
        'Legacy SCADA Protocol Exploit',
        'Attempted exploitation of legacy Modbus protocol vulnerability on RTU communication.',
        'system-compromise',
        'high',
        'closed',
        'p2-high',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        'Potential for unauthorized RTU control.',
        100000.00,
        ARRAY['Blocked suspicious network traffic', 'Isolated legacy RTUs'],
        ARRAY['Upgraded RTU firmware', 'Implemented protocol filtering'],
        ARRAY['Deployed encrypted Modbus variant', 'Enhanced network segmentation'],
        'Legacy protocols require modernization or strong compensating controls.',
        NOW() - INTERVAL '15 days',
        NOW() - INTERVAL '15 days'
    ),
    (
        v_tenant_id,
        'Unpatched Windows Vulnerability - HMI',
        'Critical Windows vulnerability (CVE-2024-XXXX) discovered on HMI workstations.',
        'system-compromise',
        'high',
        'closed',
        'p2-high',
        v_fatima_user_id,
        v_mohammed_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id],
        ARRAY[]::UUID[],
        'High risk of remote code execution.',
        60000.00,
        ARRAY['Isolated HMI network segment', 'Disabled vulnerable services'],
        ARRAY['Applied security patches', 'Verified patch integrity'],
        ARRAY['Enabled automatic patching', 'Monthly vulnerability scans'],
        'Patch management process successfully tested under pressure.',
        NOW() - INTERVAL '20 days',
        NOW() - INTERVAL '20 days'
    ),
    (
        v_tenant_id,
        'Misconfigured Firewall Rules',
        'Firewall audit revealed overly permissive rules allowing direct access between IT and OT networks.',
        'unauthorized-access',
        'medium',
        'closed',
        'p3-medium',
        v_omar_user_id,
        v_sarah_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Violation of network segmentation policy.',
        20000.00,
        ARRAY['Documented current rules', 'Disabled unnecessary rules'],
        ARRAY['Implemented least-privilege filtering', 'Added deny-by-default policy'],
        ARRAY['Quarterly firewall rule audits', 'Automated compliance checking'],
        'Firewall configuration management needs formalization.',
        NOW() - INTERVAL '25 days',
        NOW() - INTERVAL '25 days'
    ),
    (
        v_tenant_id,
        'Expired SSL Certificates - SCADA Gateway',
        'SSL certificates on SCADA gateway expired causing encrypted communication failures.',
        'system-compromise',
        'medium',
        'closed',
        'p3-medium',
        v_sarah_user_id,
        v_fatima_user_id,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        'Communication security degraded, potential for man-in-the-middle attacks.',
        30000.00,
        ARRAY['Renewed certificates', 'Temporarily allowed non-encrypted fallback'],
        NULL,
        ARRAY['Implemented certificate expiration monitoring', 'Automated renewal process'],
        'Certificate lifecycle management requires automated tracking.',
        NOW() - INTERVAL '30 days',
        NOW() - INTERVAL '30 days'
    ),
    (
        v_tenant_id,
        'Rogue Wireless Access Point Detected',
        'Unauthorized wireless access point discovered in Al Aweer control room.',
        'unauthorized-access',
        'medium',
        'closed',
        'p3-medium',
        v_mohammed_user_id,
        v_omar_user_id,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        'Potential bypass of network security controls.',
        12000.00,
        ARRAY['Removed rogue device', 'Enhanced wireless monitoring'],
        ARRAY['Investigated device ownership', 'Reviewed physical access logs'],
        ARRAY['Wireless intrusion detection system deployed', 'Regular wireless scans'],
        'Need better physical security awareness among staff.',
        NOW() - INTERVAL '35 days',
        NOW() - INTERVAL '35 days'
    ),

    -- Low Priority / Drill Incidents
    (
        v_tenant_id,
        'Security Awareness Drill - Phishing Test',
        'Simulated phishing campaign for security awareness training.',
        'unauthorized-access',
        'low',
        'resolved',
        'p4-low',
        v_fatima_user_id,
        v_sarah_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Training exercise - no actual impact.',
        0.00,
        NULL,
        NULL,
        NULL,
        '23% of users clicked simulated phishing link. Additional training scheduled.',
        NOW() - INTERVAL '40 days',
        NOW() - INTERVAL '40 days'
    ),
    (
        v_tenant_id,
        'Failed Backup Verification',
        'Automated backup verification failed for SCADA database.',
        'configuration-error',
        'low',
        'resolved',
        'p4-low',
        v_omar_user_id,
        v_fatima_user_id,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        'Backup integrity concern, no operational impact.',
        8000.00,
        ARRAY['Investigated backup failure', 'Re-ran backup process'],
        NULL,
        ARRAY['Fixed backup script error', 'Enhanced backup monitoring'],
        'Backup verification process working as designed.',
        NOW() - INTERVAL '45 days',
        NOW() - INTERVAL '45 days'
    ),
    (
        v_tenant_id,
        'Antivirus Definition Update Failure',
        'Antivirus definition updates failed on multiple HMI workstations.',
        'malware-infection',
        'low',
        'resolved',
        'p4-low',
        v_sarah_user_id,
        v_mohammed_user_id,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        'Reduced malware detection capability.',
        5000.00,
        ARRAY['Manually updated definitions', 'Restarted update service'],
        NULL,
        ARRAY['Fixed update service configuration', 'Implemented update monitoring'],
        'Automated updates require redundant verification.',
        NOW() - INTERVAL '50 days',
        NOW() - INTERVAL '50 days'
    ),
    (
        v_tenant_id,
        'Incident Response Tabletop Exercise',
        'Quarterly tabletop exercise simulating multi-site SCADA compromise.',
        'system-compromise',
        'low',
        'closed',
        'p4-low',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        'Training exercise - validated response procedures.',
        0.00,
        NULL,
        NULL,
        NULL,
        'Response time improved by 15% compared to last exercise. Communication protocols effective.',
        NOW() - INTERVAL '60 days',
        NOW() - INTERVAL '60 days'
    ),
    
    -- Additional Recent Incidents
    (
        v_tenant_id,
        'Port Scan Activity Detected',
        'Automated port scanning detected from internal network targeting protection relays.',
        'unauthorized-access',
        'medium',
        'investigating',
        'p3-medium',
        v_omar_user_id,
        v_mohammed_user_id,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        'Reconnaissance activity indicating potential attack preparation.',
        35000.00,
        ARRAY['Blocked scanning source', 'Enhanced IDS rules'],
        NULL,
        NULL,
        NULL,
        NOW() - INTERVAL '8 hours',
        NOW() - INTERVAL '7 hours'
    ),
    (
        v_tenant_id,
        'Spear Phishing - Executive Target',
        'Highly targeted spear phishing email sent to grid operations manager with fake vendor invoice.',
        'unauthorized-access',
        'high',
        'contained',
        'p2-high',
        v_sarah_user_id,
        v_fatima_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Credential theft attempt targeting high-privilege account.',
        45000.00,
        ARRAY['Alerted targeted user', 'Blocked sender', 'Enhanced executive email protection'],
        ARRAY['Analyzed email headers', 'Identified spoofed domain'],
        ARRAY['Implemented DMARC policy', 'Executive security briefing'],
        'Targeted attack indicates adversary reconnaissance of organizational structure.',
        NOW() - INTERVAL '2 days',
        NOW() - INTERVAL '2 days'
    ),
    (
        v_tenant_id,
        'Zero-Day Vulnerability Alert - IEC 61850',
        'Public disclosure of zero-day vulnerability in IEC 61850 protocol implementation.',
        'system-compromise',
        'high',
        'open',
        'p2-high',
        v_mohammed_user_id,
        v_sarah_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        'Critical vulnerability in widely deployed protocol with no patch available.',
        150000.00,
        ARRAY['Restricted IEC 61850 traffic to essential communications only', 'Enhanced monitoring'],
        NULL,
        NULL,
        'Awaiting vendor patch. Compensating controls implemented.',
        NOW() - INTERVAL '1 day',
        NOW() - INTERVAL '20 hours'
    ),
    (
        v_tenant_id,
        'Supply Chain Security Concern',
        'Suspicious firmware detected in newly delivered network switches from vendor.',
        'system-compromise',
        'medium',
        'investigating',
        'p3-medium',
        v_omar_user_id,
        v_sarah_user_id,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        'Potential backdoor in network infrastructure equipment.',
        85000.00,
        ARRAY['Quarantined suspect equipment', 'Initiated vendor investigation'],
        ARRAY['Forensic analysis of firmware', 'Comparison with known-good version'],
        NULL,
        NULL,
        NOW() - INTERVAL '3 days',
        NOW() - INTERVAL '3 days'
    ),
    (
        v_tenant_id,
        'LOG4J Vulnerability Assessment',
        'Emergency assessment for Apache Log4j vulnerability (Log4Shell) across all systems.',
        'system-compromise',
        'high',
        'closed',
        'p2-high',
        v_fatima_user_id,
        v_mohammed_user_id,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        'Widespread vulnerability requiring immediate assessment.',
        120000.00,
        ARRAY['Scanned all systems for Java applications', 'Isolated vulnerable systems'],
        ARRAY['Patched affected applications', 'Verified remediation'],
        ARRAY['Enhanced vulnerability management process', 'Vendor security requirements updated'],
        'Rapid coordination between IT and OT teams was effective.',
        NOW() - INTERVAL '90 days',
        NOW() - INTERVAL '90 days'
    );

END $$;

COMMIT;