-- Seed data for transmission security risks
-- Description: Populate security risks for power transmission cybersecurity
-- Requirements: 4.6, 10.4

-- Insert transmission-specific security risks
INSERT INTO security_risks (
  tenant_id,
  risk_id,
  risk_name,
  risk_description,
  risk_category,
  risk_subcategory,
  threat_scenario,
  threat_actor,
  attack_vector,
  affected_asset_types,
  affected_protocols,
  inherent_likelihood,
  inherent_impact,
  control_effectiveness,
  residual_likelihood,
  residual_impact,
  treatment_strategy,
  status,
  treatment_owner,
  next_assessment_date,
  next_monitoring_date,
  identified_by,
  notes
) VALUES 
-- Critical Cybersecurity Risk
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'RISK-TX-001',
  'IEC 61850 GOOSE Message Manipulation',
  'Unauthorized manipulation of IEC 61850 GOOSE messages could cause protection relay misoperation, leading to cascading grid failures and equipment damage.',
  'cyber-attack',
  'protocol-manipulation',
  'Attacker intercepts and modifies GOOSE messages to cause protection relay misoperation',
  'nation-state',
  ARRAY['network-interception', 'protocol-manipulation', 'man-in-the-middle'],
  ARRAY['protection-relays', 'substation-automation', 'transmission-lines'],
  ARRAY['IEC-61850', 'GOOSE'],
  'medium',
  'catastrophic',
  'partially-effective',
  'medium',
  'major',
  'mitigate',
  'mitigating',
  'Cybersecurity Team Lead',
  '2024-03-15T10:00:00Z',
  '2024-02-15T10:00:00Z',
  'Security Analyst',
  'Requires immediate implementation of IEC 62351 security extensions for encrypted GOOSE communications'
),

-- High Grid Stability Risk
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'RISK-TX-002',
  'SCADA System Compromise',
  'Compromise of SCADA systems could allow attackers to manipulate grid operations, causing load shedding, equipment damage, or blackouts.',
  'cyber-attack',
  'system-compromise',
  'Advanced persistent threat gains access to SCADA systems through spear-phishing or supply chain attack',
  'nation-state',
  ARRAY['spear-phishing', 'supply-chain-attack', 'lateral-movement'],
  ARRAY['scada-systems', 'control-centers', 'transmission-substations'],
  ARRAY['DNP3', 'IEC-60870-5-104'],
  'medium',
  'major',
  'partially-effective',
  'medium',
  'major',
  'mitigate',
  'assessed',
  'Operations Manager',
  '2024-04-01T14:00:00Z',
  '2024-02-01T14:00:00Z',
  'Security Analyst',
  'Multi-factor authentication and network micro-segmentation implementation in progress'
),

-- Medium Insider Threat Risk
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'RISK-TX-003',
  'Privileged User Account Misuse',
  'Misuse of privileged accounts by insiders could result in unauthorized configuration changes, data theft, or system sabotage.',
  'insider-threat',
  'privilege-abuse',
  'Malicious insider uses privileged access to modify protection settings or steal sensitive operational data',
  'insider',
  ARRAY['privilege-escalation', 'data-exfiltration', 'system-sabotage'],
  ARRAY['control-systems', 'protection-settings', 'operational-data'],
  ARRAY['IEC-61850', 'DNP3'],
  'low',
  'major',
  'effective',
  'low',
  'moderate',
  'mitigate',
  'monitoring',
  'Security Manager',
  '2024-05-01T09:00:00Z',
  '2024-02-20T09:00:00Z',
  'Security Analyst',
  'Privileged access management system deployment scheduled for Q2 2024'
),

-- High Equipment Failure Risk
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'RISK-TX-004',
  'Protection Relay Firmware Vulnerabilities',
  'Unpatched firmware vulnerabilities in protection relays could be exploited to cause relay malfunction or unauthorized access to protection settings.',
  'system-vulnerability',
  'firmware-vulnerability',
  'Attacker exploits known firmware vulnerability to gain control of protection relay',
  'criminal',
  ARRAY['remote-exploitation', 'firmware-manipulation', 'configuration-change'],
  ARRAY['protection-relays', 'differential-protection', 'distance-protection'],
  ARRAY['IEC-61850', 'DNP3'],
  'medium',
  'major',
  'partially-effective',
  'low',
  'moderate',
  'mitigate',
  'identified',
  'Engineering Manager',
  '2024-03-30T16:00:00Z',
  '2024-02-28T16:00:00Z',
  'Security Analyst',
  'Firmware vulnerability assessment and patching program under development'
),

-- Medium System Vulnerability Risk
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'RISK-TX-005',
  'HMI Workstation Security Gaps',
  'Security vulnerabilities in Human-Machine Interface workstations could provide attack vectors into the control network.',
  'system-vulnerability',
  'endpoint-vulnerability',
  'Attacker compromises HMI workstation through malware or unpatched vulnerability',
  'criminal',
  ARRAY['malware-infection', 'unpatched-vulnerability', 'usb-attack'],
  ARRAY['hmi-workstations', 'operator-interfaces', 'control-network'],
  ARRAY['Windows-protocols', 'RDP'],
  'medium',
  'moderate',
  'effective',
  'low',
  'minor',
  'accept',
  'monitoring',
  'IT Security Manager',
  '2024-06-01T11:00:00Z',
  '2024-03-01T11:00:00Z',
  'Security Analyst',
  'Risk accepted with current controls, continuous monitoring in place'
);

-- Insert sample risk assessments
INSERT INTO risk_assessments (
  tenant_id,
  risk_id,
  assessment_date,
  assessment_type,
  assessor_name,
  assessment_method,
  likelihood,
  impact,
  risk_score,
  risk_level,
  findings,
  control_effectiveness_assessment,
  recommendations
) VALUES
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_risks WHERE risk_id = 'RISK-TX-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2024-01-15T10:00:00Z',
  'initial',
  'Senior Security Analyst',
  'qualitative',
  'medium',
  'catastrophic',
  95.0,
  'critical',
  'Medium likelihood based on known attack vectors against IEC 61850 protocols and increasing targeting of critical infrastructure',
  'Current controls provide basic protection but lack protocol-level security. Network segmentation partially effective.',
  ARRAY['Implement IEC 62351 security extensions', 'Deploy protocol-aware firewalls', 'Enhance network monitoring']
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_risks WHERE risk_id = 'RISK-TX-002' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2024-01-20T14:00:00Z',
  'initial',
  'Security Consultant',
  'semi-quantitative',
  'medium',
  'major',
  80.0,
  'high',
  'Medium likelihood based on threat intelligence indicating increased APT activity targeting power sector',
  'Legacy SCADA systems present significant attack surface. Current controls need enhancement.',
  ARRAY['Implement multi-factor authentication', 'Deploy micro-segmentation', 'Upgrade SCADA security']
);

-- Insert sample risk mitigation actions
INSERT INTO risk_mitigation_actions (
  tenant_id,
  risk_id,
  action_name,
  action_description,
  action_type,
  priority,
  responsible_party,
  planned_completion_date,
  status,
  estimated_cost,
  notes
) VALUES
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_risks WHERE risk_id = 'RISK-TX-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'Deploy IEC 62351 Security Extensions',
  'Implement IEC 62351 security extensions to provide authentication and encryption for IEC 61850 GOOSE and MMS communications',
  'technology',
  'critical',
  'Engineering Team Lead',
  '2024-09-30T23:59:59Z',
  'in-progress',
  250000.00,
  'Phase 1: Pilot deployment at Dubai Main Substation - 60% complete'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_risks WHERE risk_id = 'RISK-TX-002' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'Implement Multi-Factor Authentication',
  'Deploy MFA for all SCADA system access including operators, engineers, and maintenance personnel',
  'process-change',
  'high',
  'Cybersecurity Team',
  '2024-06-30T23:59:59Z',
  'planned',
  75000.00,
  'Requirements gathering and vendor selection in progress'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_risks WHERE risk_id = 'RISK-TX-003' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'Deploy Privileged Access Management',
  'Implement PAM solution to control and monitor all privileged access to critical transmission systems',
  'technology',
  'high',
  'IT Security Manager',
  '2024-08-31T23:59:59Z',
  'in-progress',
  150000.00,
  'PAM solution selected, deployment phase initiated'
);