-- Seed data for transmission security controls
-- Description: Populate security control library for power transmission cybersecurity
-- Requirements: 4.2, 10.4

-- Insert transmission-specific security controls
INSERT INTO security_controls (
  tenant_id,
  control_id,
  control_name,
  control_description,
  control_type,
  category,
  subcategory,
  domain,
  standard_id,
  standard_reference,
  iec_62443_mapping,
  nerc_cip_mapping,
  nist_csf_mapping,
  implementation_status,
  implementation_percentage,
  implementation_approach,
  implementation_date,
  effectiveness,
  effectiveness_score,
  last_assessment_date,
  next_assessment_date,
  applies_to_asset_types,
  applies_to_zones,
  applies_to_protocols,
  criticality,
  responsible_party,
  responsible_role,
  evidence_required,
  evidence_provided,
  validation_method,
  validation_frequency_days,
  last_validated,
  validated_by,
  testing_required,
  testing_frequency_days,
  last_tested,
  next_test_date,
  test_results,
  implementation_cost_estimate,
  implementation_effort_hours,
  annual_maintenance_cost,
  status,
  notes,
  tags
) VALUES 
-- Access Control - Multi-Factor Authentication
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'TRANS-AC-001',
  'Multi-Factor Authentication for SCADA Access',
  'Implement multi-factor authentication for all access to SCADA systems, HMI workstations, and protection relay configuration interfaces.',
  'preventive',
  'Access Control',
  'Authentication',
  'Identity',
  (SELECT id FROM compliance_standards WHERE name = 'IEC 62443' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'IEC 62443-3-3 SR 1.1',
  'SR 1.1',
  'CIP-005-6 R2',
  'PR.AC-1',
  'implemented',
  100.00,
  'Hardware tokens and smart cards deployed for all transmission operations personnel',
  '2023-12-15T10:00:00Z',
  'effective',
  95.00,
  '2024-01-15T10:00:00Z',
  '2024-07-15T10:00:00Z',
  ARRAY['scada-systems', 'hmi-workstations', 'protection-relays'],
  ARRAY['substation-control', 'scada-network'],
  ARRAY['IEC-61850', 'DNP3', 'IEC-60870-5-104'],
  'safety-critical',
  'Cybersecurity Team Lead',
  'Security Administrator',
  ARRAY['MFA policy document', 'Token deployment records', 'Authentication logs'],
  ARRAY['MFA deployment guide v2.1', 'Token inventory spreadsheet', 'Authentication audit logs Q4-2023'],
  'Automated log analysis and manual testing',
  90,
  '2024-01-15T10:00:00Z',
  'Security Auditor',
  true,
  180,
  '2024-01-10T14:00:00Z',
  '2024-07-10T14:00:00Z',
  'All authentication tests passed. Token failure rate < 0.1%',
  125000.00,
  480,
  15000.00,
  'active',
  'Successfully deployed across all transmission substations and control centers',
  ARRAY['authentication', 'access-control', 'scada', 'critical']
),

-- Network Security - Protocol Security
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'TRANS-NS-001',
  'IEC 62351 Security Extensions',
  'Implement IEC 62351 security extensions to provide authentication, authorization, and encryption for IEC 61850 communications.',
  'preventive',
  'Network Security',
  'Communication Protection',
  'Network',
  (SELECT id FROM compliance_standards WHERE name = 'IEC 62443' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'IEC 62443-3-3 SR 3.1',
  'SR 3.1',
  'CIP-005-6 R1',
  'PR.DS-2',
  'partial',
  35.00,
  'Pilot deployment at Dubai Main Substation, rollout to remaining substations in progress',
  null,
  'partially-effective',
  35.00,
  '2024-01-20T09:00:00Z',
  '2024-07-20T09:00:00Z',
  ARRAY['protection-relays', 'substation-automation', 'merging-units'],
  ARRAY['substation-control', 'protection-systems'],
  ARRAY['IEC-61850', 'GOOSE', 'MMS'],
  'safety-critical',
  'Engineering Team Lead',
  'Protection Engineer',
  ARRAY['IEC 62351 implementation plan', 'Certificate management procedures', 'Encrypted communication tests'],
  ARRAY['Pilot implementation report', 'Certificate authority setup'],
  'Protocol analysis and penetration testing',
  60,
  '2024-01-20T09:00:00Z',
  'Security Consultant',
  true,
  90,
  '2024-01-15T11:00:00Z',
  '2024-04-15T11:00:00Z',
  'Pilot site: GOOSE encryption functional, MMS authentication implemented',
  850000.00,
  2400,
  45000.00,
  'active',
  'Critical control for protection system security. Phase 1 complete at pilot site.',
  ARRAY['encryption', 'protocol-security', 'iec-61850', 'critical']
),

-- Endpoint Security - Protection Relay Hardening
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'TRANS-EP-001',
  'Protection Relay Security Hardening',
  'Implement security hardening measures for protection relays including firmware updates, secure configuration, and access controls.',
  'preventive',
  'Endpoint Security',
  'Device Hardening',
  'Endpoint',
  (SELECT id FROM compliance_standards WHERE name = 'IEEE 1686' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'IEEE 1686-2013 Section 5',
  'SR 7.1',
  'CIP-007-6 R2',
  'PR.IP-1',
  'implemented',
  85.00,
  'Standardized security configuration applied to all new relay installations',
  '2023-11-30T16:00:00Z',
  'effective',
  85.00,
  '2024-01-10T13:00:00Z',
  '2024-07-10T13:00:00Z',
  ARRAY['protection-relays', 'differential-protection', 'distance-protection'],
  ARRAY['substation-control', 'protection-systems'],
  ARRAY['IEC-61850', 'DNP3'],
  'safety-critical',
  'Protection Engineer',
  'Senior Protection Engineer',
  ARRAY['Relay hardening checklist', 'Firmware update records', 'Configuration baselines'],
  ARRAY['Hardening standard v1.2', 'Firmware inventory Q4-2023', 'Configuration audit report'],
  'Configuration compliance scanning and manual review',
  120,
  '2024-01-10T13:00:00Z',
  'Protection Engineer',
  true,
  180,
  '2023-12-20T10:00:00Z',
  '2024-06-20T10:00:00Z',
  '85% of relays meet hardening requirements. Legacy relays require upgrade.',
  75000.00,
  320,
  8000.00,
  'active',
  'Ongoing program with quarterly compliance assessments',
  ARRAY['hardening', 'protection-relays', 'firmware', 'configuration']
),

-- Monitoring and Detection - SIEM Integration
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'TRANS-MD-001',
  'SCADA Security Event Monitoring',
  'Implement security event monitoring and logging for SCADA systems with integration to central SIEM platform.',
  'detective',
  'Monitoring and Detection',
  'Security Monitoring',
  'Network',
  (SELECT id FROM compliance_standards WHERE name = 'NERC CIP' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'CIP-007-6 R4',
  'SR 6.1',
  'CIP-007-6 R4',
  'DE.CM-1',
  'implemented',
  90.00,
  'Centralized logging and SIEM correlation for all transmission SCADA systems',
  '2023-10-15T12:00:00Z',
  'effective',
  88.00,
  '2024-01-05T15:00:00Z',
  '2024-07-05T15:00:00Z',
  ARRAY['scada-systems', 'control-centers', 'hmi-workstations'],
  ARRAY['scada-network', 'substation-control'],
  ARRAY['DNP3', 'IEC-60870-5-104', 'IEC-61850'],
  'operational-critical',
  'Security Operations Manager',
  'SOC Analyst',
  ARRAY['SIEM configuration documentation', 'Log retention policies', 'Alert response procedures'],
  ARRAY['SIEM deployment guide', 'Log retention policy v1.1', 'SOC playbook v2.0'],
  'SIEM dashboard review and alert validation',
  30,
  '2024-01-05T15:00:00Z',
  'SOC Manager',
  true,
  90,
  '2024-01-01T09:00:00Z',
  '2024-04-01T09:00:00Z',
  'SIEM processing 2.5M events/day with 99.2% uptime. Alert accuracy 94%.',
  180000.00,
  640,
  25000.00,
  'active',
  'Continuous monitoring with 24/7 SOC coverage',
  ARRAY['monitoring', 'siem', 'logging', 'detection']
),

-- Incident Response - Cyber Incident Response
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'TRANS-IR-001',
  'Transmission Cyber Incident Response',
  'Establish dedicated incident response procedures for transmission system cybersecurity incidents with coordination between IT and OT teams.',
  'corrective',
  'Incident Response',
  'Response Planning',
  'Application',
  (SELECT id FROM compliance_standards WHERE name = 'NIST CSF' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'RS.RP-1',
  'SR 6.2',
  'CIP-008-6 R1',
  'RS.RP-1',
  'implemented',
  95.00,
  'Dedicated transmission cyber incident response team with 24/7 on-call rotation',
  '2023-09-20T14:00:00Z',
  'effective',
  92.00,
  '2024-01-12T11:00:00Z',
  '2024-07-12T11:00:00Z',
  ARRAY['scada-systems', 'protection-relays', 'control-centers'],
  ARRAY['substation-control', 'scada-network', 'protection-systems'],
  ARRAY['IEC-61850', 'DNP3', 'IEC-60870-5-104'],
  'safety-critical',
  'Incident Response Manager',
  'Cyber Incident Commander',
  ARRAY['Incident response plan', 'Team contact lists', 'Escalation procedures'],
  ARRAY['IR plan v3.1', 'Team roster Q1-2024', 'Escalation matrix'],
  'Tabletop exercises and incident simulations',
  180,
  '2024-01-12T11:00:00Z',
  'Emergency Response Coordinator',
  true,
  90,
  '2023-12-15T13:00:00Z',
  '2024-03-15T13:00:00Z',
  'Tabletop exercise completed. Response time target: <30 minutes achieved.',
  45000.00,
  160,
  12000.00,
  'active',
  'Regular training and exercises conducted quarterly',
  ARRAY['incident-response', 'emergency', 'coordination', 'critical']
);

-- Insert control implementations for specific sites/assets
INSERT INTO control_implementations (
  tenant_id,
  control_id,
  implementation_name,
  implementation_description,
  site_id,
  technology_used,
  tools_used,
  configuration_details,
  status,
  effectiveness,
  implementation_date,
  last_verified,
  next_verification,
  implemented_by,
  verified_by,
  notes
) VALUES
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_controls WHERE control_id = 'TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'MFA - Dubai Main Substation',
  'Multi-factor authentication implementation at Dubai Main 400kV substation',
  (SELECT id FROM sites WHERE name = 'Dubai Main Substation' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'RSA SecurID tokens and smart cards',
  ARRAY['RSA Authentication Manager', 'Active Directory', 'RADIUS'],
  '{"token_type": "hardware", "backup_method": "smart_card", "session_timeout": 480, "max_failed_attempts": 3}',
  'implemented',
  'effective',
  '2023-12-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-04-15T10:00:00Z',
  'Security Administrator',
  'Security Auditor',
  'Primary implementation site for MFA rollout'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_controls WHERE control_id = 'TRANS-NS-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'IEC 62351 - Dubai Main Pilot',
  'IEC 62351 security extensions pilot implementation',
  (SELECT id FROM sites WHERE name = 'Dubai Main Substation' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'IEC 62351 security gateway and certificate authority',
  ARRAY['Schneider Electric Security Gateway', 'Microsoft CA', 'Wireshark Protocol Analyzer'],
  '{"encryption_algorithm": "AES-256", "key_management": "PKI", "certificate_validity": 365, "goose_encryption": true}',
  'partial',
  'partially-effective',
  null,
  '2024-01-20T09:00:00Z',
  '2024-04-20T09:00:00Z',
  'Protection Engineer',
  'Security Consultant',
  'Pilot site for IEC 62351 deployment. GOOSE encryption active, MMS authentication in testing.'
);

-- Insert sample test results
INSERT INTO control_test_results (
  tenant_id,
  control_id,
  implementation_id,
  test_date,
  test_type,
  test_name,
  test_description,
  tester_name,
  test_duration_minutes,
  test_methodology,
  result,
  effectiveness_rating,
  findings,
  issues_found,
  recommendations,
  remediation_required,
  remediation_priority,
  evidence_files,
  evidence_notes,
  follow_up_required,
  follow_up_date,
  notes
) VALUES
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_controls WHERE control_id = 'TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM control_implementations WHERE implementation_name = 'MFA - Dubai Main Substation' LIMIT 1),
  '2024-01-10T14:00:00Z',
  'automated',
  'MFA Authentication Test',
  'Automated testing of multi-factor authentication for SCADA system access',
  'Security Test Engineer',
  45,
  'Automated authentication attempts with valid and invalid credentials',
  'pass',
  'effective',
  'All authentication tests successful. Token validation working correctly.',
  ARRAY[]::text[],
  ARRAY['Continue regular testing', 'Monitor token failure rates'],
  false,
  null,
  ARRAY['mfa_test_results_20240110.pdf', 'authentication_logs_20240110.txt'],
  'Test covered 50 user accounts across all shifts',
  false,
  null,
  'Excellent results. MFA system performing as expected.'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_controls WHERE control_id = 'TRANS-NS-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM control_implementations WHERE implementation_name = 'IEC 62351 - Dubai Main Pilot' LIMIT 1),
  '2024-01-15T11:00:00Z',
  'manual',
  'IEC 62351 Protocol Security Test',
  'Manual testing of IEC 62351 encryption and authentication for GOOSE messages',
  'Security Consultant',
  120,
  'Protocol analysis using Wireshark and custom test tools',
  'partial',
  'partially-effective',
  'GOOSE encryption working correctly. MMS authentication partially implemented.',
  ARRAY['MMS authentication not fully configured', 'Certificate renewal process needs documentation'],
  ARRAY['Complete MMS authentication configuration', 'Document certificate management procedures'],
  true,
  'medium',
  ARRAY['protocol_analysis_20240115.pcap', 'security_test_report_20240115.pdf'],
  'Detailed protocol analysis shows encryption active for GOOSE, MMS needs completion',
  true,
  '2024-02-15T11:00:00Z',
  'Pilot implementation progressing well. MMS authentication completion required.'
);