-- Seed data for transmission security policies
-- Description: Populate security policies for power transmission cybersecurity
-- Requirements: 4.3, 10.4

-- Insert transmission-specific security policies
INSERT INTO security_policies (
  tenant_id,
  policy_id,
  policy_name,
  policy_description,
  policy_type,
  version,
  version_date,
  status,
  effective_date,
  review_date,
  expiration_date,
  review_frequency_months,
  scope,
  enforcement_level,
  applies_to_sites,
  applies_to_zones,
  applies_to_roles,
  applies_to_asset_types,
  policy_statement,
  purpose,
  objectives,
  requirements,
  procedures,
  exceptions_allowed,
  exception_criteria,
  related_standards,
  related_controls,
  regulatory_requirements,
  created_by,
  reviewed_by,
  approved_by,
  review_date_actual,
  approval_date,
  approval_notes,
  policy_owner,
  policy_owner_role,
  responsible_parties,
  document_url,
  document_version,
  related_documents,
  training_required,
  training_materials,
  compliance_mandatory,
  compliance_tracking_enabled,
  last_compliance_check,
  compliance_rate,
  tags,
  notes
) VALUES 
-- Access Control Policy
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'POL-TRANS-AC-001',
  'Transmission System Access Control Policy',
  'Defines access control requirements for all transmission system components including SCADA, protection relays, and substation automation systems.',
  'Access Control',
  '2.1',
  '2024-01-01T00:00:00Z',
  'active',
  '2024-01-01T00:00:00Z',
  '2024-07-01T00:00:00Z',
  '2025-01-01T00:00:00Z',
  12,
  'transmission',
  'mandatory',
  null, -- Applies to all sites
  ARRAY['substation-control', 'scada-network', 'protection-systems'],
  ARRAY['transmission-operator', 'protection-engineer', 'maintenance-technician', 'system-administrator'],
  ARRAY['scada-systems', 'protection-relays', 'hmi-workstations', 'substation-automation'],
  'All access to transmission system components must be authenticated, authorized, and logged. Multi-factor authentication is required for all privileged access to critical systems.',
  'To ensure secure and controlled access to transmission system components, protecting against unauthorized access that could compromise grid stability and safety.',
  ARRAY[
    'Implement strong authentication mechanisms for all system access',
    'Enforce role-based access control based on job functions',
    'Maintain comprehensive access logs and audit trails',
    'Regularly review and update access permissions',
    'Ensure segregation of duties for critical operations'
  ],
  ARRAY[
    'Multi-factor authentication required for all SCADA system access',
    'Role-based access control must be implemented for all transmission systems',
    'Access permissions must be reviewed quarterly',
    'All access attempts must be logged and monitored',
    'Privileged accounts must be managed through dedicated PAM system',
    'Emergency access procedures must be documented and tested',
    'Access must be revoked immediately upon role change or termination'
  ],
  'Access control procedures are documented in the Transmission System Access Control Procedures manual. All access requests must be approved through the established workflow in the IT service management system.',
  true,
  'Emergency access may be granted for critical system restoration activities, subject to immediate notification to the Security Manager and subsequent review within 24 hours.',
  ARRAY[
    (SELECT id FROM compliance_standards WHERE name = 'IEC 62443' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
    (SELECT id FROM compliance_standards WHERE name = 'NERC CIP' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY[
    (SELECT id FROM security_controls WHERE control_id = 'TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY['NERC CIP-005-6', 'IEC 62443-3-3 SR 1.1', 'IEC 62443-3-3 SR 2.1'],
  (SELECT id FROM security_users WHERE username = 'ahmed.almansouri' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2023-12-15T10:00:00Z',
  '2023-12-20T14:00:00Z',
  'Policy approved with minor revisions to emergency access procedures',
  'Chief Information Security Officer',
  'CISO',
  ARRAY['Cybersecurity Team Lead', 'Operations Manager', 'Engineering Manager'],
  'https://policies.dewa.gov.ae/transmission/access-control-v2.1.pdf',
  '2.1',
  ARRAY['Transmission System Security Standards', 'Emergency Response Procedures', 'User Access Management Guide'],
  true,
  ARRAY['Access Control Training Module', 'MFA Setup Guide', 'Role-Based Access Control Overview'],
  true,
  true,
  '2024-01-15T09:00:00Z',
  94.50,
  ARRAY['access-control', 'authentication', 'authorization', 'critical'],
  'Updated to include new MFA requirements and PAM system integration'
),

-- Network Security Policy
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'POL-TRANS-NS-001',
  'Transmission Network Security Policy',
  'Establishes network security requirements for transmission system communications including SCADA networks, protection system communications, and substation networks.',
  'Network Security',
  '1.3',
  '2023-11-01T00:00:00Z',
  'active',
  '2023-11-01T00:00:00Z',
  '2024-05-01T00:00:00Z',
  '2024-11-01T00:00:00Z',
  12,
  'transmission',
  'mandatory',
  null, -- Applies to all sites
  ARRAY['scada-network', 'substation-control', 'protection-systems'],
  ARRAY['network-engineer', 'cybersecurity-analyst', 'system-administrator'],
  ARRAY['network-equipment', 'firewalls', 'switches', 'communication-gateways'],
  'All transmission system networks must be secured through network segmentation, encryption, and continuous monitoring. Critical communications must use approved secure protocols.',
  'To protect transmission system networks from cyber threats and ensure the integrity and availability of critical communications.',
  ARRAY[
    'Implement network segmentation to isolate critical systems',
    'Deploy encryption for sensitive communications',
    'Establish continuous network monitoring and threat detection',
    'Maintain network security baselines and configurations',
    'Ensure secure remote access capabilities'
  ],
  ARRAY[
    'Network segmentation must separate SCADA, protection, and corporate networks',
    'IEC 62351 security extensions must be implemented for IEC 61850 communications',
    'All network devices must be hardened according to security standards',
    'Network traffic must be monitored and analyzed for anomalies',
    'Firewalls must be configured with deny-by-default rules',
    'VPN access must use multi-factor authentication',
    'Network configuration changes must be approved and documented'
  ],
  'Network security procedures are detailed in the Network Security Implementation Guide. All network changes must follow the established change management process.',
  true,
  'Temporary network configuration changes may be permitted for emergency restoration activities, subject to immediate security review and approval within 4 hours.',
  ARRAY[
    (SELECT id FROM compliance_standards WHERE name = 'IEC 62443' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
    (SELECT id FROM compliance_standards WHERE name = 'NERC CIP' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY[
    (SELECT id FROM security_controls WHERE control_id = 'TRANS-NS-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY['NERC CIP-005-6', 'IEC 62443-3-3 SR 3.1', 'IEC 62443-3-3 SR 4.1'],
  (SELECT id FROM security_users WHERE username = 'sarah.alnuaimi' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2023-10-20T11:00:00Z',
  '2023-10-25T15:00:00Z',
  'Policy approved with emphasis on IEC 62351 implementation timeline',
  'Network Security Manager',
  'Network Security Manager',
  ARRAY['Network Engineering Team', 'Cybersecurity Team', 'Operations Team'],
  'https://policies.dewa.gov.ae/transmission/network-security-v1.3.pdf',
  '1.3',
  ARRAY['Network Hardening Standards', 'IEC 62351 Implementation Guide', 'Network Monitoring Procedures'],
  true,
  ARRAY['Network Security Fundamentals', 'IEC 62351 Training', 'Firewall Management'],
  true,
  true,
  '2024-01-10T14:00:00Z',
  87.20,
  ARRAY['network-security', 'encryption', 'monitoring', 'protocols'],
  'Updated to include IEC 62351 requirements and enhanced monitoring capabilities'
),

-- Incident Response Policy
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'POL-TRANS-IR-001',
  'Transmission Cybersecurity Incident Response Policy',
  'Defines incident response procedures for cybersecurity incidents affecting transmission system operations, including detection, response, recovery, and lessons learned.',
  'Incident Response',
  '3.0',
  '2023-09-15T00:00:00Z',
  'active',
  '2023-09-15T00:00:00Z',
  '2024-03-15T00:00:00Z',
  '2024-09-15T00:00:00Z',
  12,
  'transmission',
  'mandatory',
  null, -- Applies to all sites
  ARRAY['substation-control', 'scada-network', 'protection-systems', 'corporate-network'],
  ARRAY['incident-commander', 'security-analyst', 'operations-manager', 'engineering-manager'],
  ARRAY['scada-systems', 'protection-relays', 'control-centers', 'communication-systems'],
  'All cybersecurity incidents affecting transmission systems must be promptly detected, reported, contained, and resolved following established procedures to minimize impact on grid operations.',
  'To ensure rapid and effective response to cybersecurity incidents that could impact transmission system reliability, safety, and security.',
  ARRAY[
    'Establish 24/7 incident detection and response capabilities',
    'Minimize incident impact on transmission system operations',
    'Preserve evidence for forensic analysis and regulatory reporting',
    'Coordinate response between IT, OT, and operations teams',
    'Implement lessons learned to prevent future incidents'
  ],
  ARRAY[
    'Incidents must be detected and reported within 15 minutes of occurrence',
    'Incident response team must be activated within 30 minutes',
    'Initial containment actions must begin within 1 hour',
    'Regulatory notifications must be made within required timeframes',
    'All incidents must be documented and analyzed for lessons learned',
    'Recovery procedures must prioritize safety and system stability',
    'Post-incident reviews must be conducted within 72 hours'
  ],
  'Detailed incident response procedures are documented in the Transmission Cyber Incident Response Plan. Emergency contact information and escalation procedures are maintained in the incident response toolkit.',
  false,
  'No exceptions permitted for incident response requirements due to safety and regulatory obligations.',
  ARRAY[
    (SELECT id FROM compliance_standards WHERE name = 'NERC CIP' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
    (SELECT id FROM compliance_standards WHERE name = 'NIST CSF' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY[
    (SELECT id FROM security_controls WHERE control_id = 'TRANS-IR-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY['NERC CIP-008-6', 'NIST CSF RS.RP-1', 'NIST CSF RS.CO-1'],
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2023-08-30T16:00:00Z',
  '2023-09-05T10:00:00Z',
  'Policy approved with enhanced coordination procedures between IT and OT teams',
  'Emergency Response Manager',
  'Emergency Response Manager',
  ARRAY['Incident Response Team', 'Operations Control Center', 'Cybersecurity Team', 'Engineering Team'],
  'https://policies.dewa.gov.ae/transmission/incident-response-v3.0.pdf',
  '3.0',
  ARRAY['Cyber Incident Response Plan', 'Emergency Contact Directory', 'Regulatory Reporting Guide'],
  true,
  ARRAY['Incident Response Training', 'Tabletop Exercise Materials', 'Crisis Communication Guide'],
  true,
  true,
  '2024-01-12T08:00:00Z',
  98.70,
  ARRAY['incident-response', 'emergency', 'coordination', 'critical'],
  'Major revision to align with updated NERC CIP requirements and enhance OT/IT coordination'
),

-- Data Protection Policy
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  'POL-TRANS-DP-001',
  'Transmission System Data Protection Policy',
  'Establishes data protection and privacy requirements for transmission system operational data, including SCADA data, protection settings, and system configurations.',
  'Data Protection',
  '1.2',
  '2023-10-01T00:00:00Z',
  'active',
  '2023-10-01T00:00:00Z',
  '2024-04-01T00:00:00Z',
  '2024-10-01T00:00:00Z',
  12,
  'transmission',
  'mandatory',
  null, -- Applies to all sites
  ARRAY['scada-network', 'substation-control', 'corporate-network'],
  ARRAY['data-custodian', 'system-administrator', 'operations-analyst'],
  ARRAY['databases', 'historians', 'backup-systems', 'archive-systems'],
  'All transmission system data must be classified, protected, and managed according to its sensitivity and criticality to ensure confidentiality, integrity, and availability.',
  'To protect sensitive transmission system data from unauthorized access, modification, or disclosure while ensuring availability for operational needs.',
  ARRAY[
    'Classify all transmission system data based on sensitivity and criticality',
    'Implement appropriate protection measures for each data classification',
    'Ensure secure data backup and recovery capabilities',
    'Maintain data retention and disposal procedures',
    'Monitor data access and usage patterns'
  ],
  ARRAY[
    'All data must be classified as Public, Internal, Confidential, or Restricted',
    'Confidential and Restricted data must be encrypted at rest and in transit',
    'Data access must be logged and monitored continuously',
    'Backup data must be tested and verified regularly',
    'Data retention periods must comply with regulatory requirements',
    'Secure data disposal procedures must be followed',
    'Data sharing agreements must be established for external parties'
  ],
  'Data protection procedures are detailed in the Data Classification and Handling Guide. Data custodians are responsible for implementing appropriate protection measures.',
  true,
  'Temporary data access may be granted for emergency operations, subject to immediate logging and subsequent review within 24 hours.',
  ARRAY[
    (SELECT id FROM compliance_standards WHERE name = 'ISO 27001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1)
  ],
  ARRAY[]::uuid[],
  ARRAY['ISO 27001 A.8.2.1', 'ISO 27001 A.8.2.3', 'NERC CIP-011-2'],
  (SELECT id FROM security_users WHERE username = 'abdullah.alshamsi' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2023-09-25T13:00:00Z',
  '2023-09-28T17:00:00Z',
  'Policy approved with clarifications on data classification criteria',
  'Data Protection Officer',
  'Data Protection Officer',
  ARRAY['Data Custodians', 'System Administrators', 'Database Administrators'],
  'https://policies.dewa.gov.ae/transmission/data-protection-v1.2.pdf',
  '1.2',
  ARRAY['Data Classification Guide', 'Encryption Standards', 'Backup and Recovery Procedures'],
  true,
  ARRAY['Data Classification Training', 'Encryption Implementation', 'Privacy Awareness'],
  true,
  true,
  '2024-01-08T12:00:00Z',
  91.80,
  ARRAY['data-protection', 'privacy', 'classification', 'encryption'],
  'Updated to include enhanced encryption requirements and data sharing protocols'
);

-- Insert policy acknowledgments for key personnel
INSERT INTO policy_acknowledgments (
  tenant_id,
  policy_id,
  user_id,
  policy_version,
  acknowledged_date,
  acknowledgment_method,
  training_completed,
  training_completion_date,
  training_score,
  compliant,
  compliance_notes,
  last_compliance_check,
  notes
) VALUES
-- Access Control Policy Acknowledgments
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'khalid.almarri' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2.1',
  '2024-01-05T09:00:00Z',
  'electronic',
  true,
  '2024-01-05T10:30:00Z',
  95.0,
  true,
  'Completed MFA setup and role-based access training',
  '2024-01-15T09:00:00Z',
  'Excellent understanding of access control requirements'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'omar.alfalasi' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2.1',
  '2024-01-03T14:00:00Z',
  'electronic',
  true,
  '2024-01-03T15:45:00Z',
  88.0,
  true,
  'Completed training, requires follow-up on emergency access procedures',
  '2024-01-15T09:00:00Z',
  'Good understanding, minor clarification needed on emergency procedures'
),

-- Network Security Policy Acknowledgments
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-NS-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'sarah.alnuaimi' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '1.3',
  '2023-11-10T11:00:00Z',
  'electronic',
  true,
  '2023-11-10T13:30:00Z',
  92.0,
  true,
  'Completed IEC 62351 training and network segmentation review',
  '2024-01-10T14:00:00Z',
  'Strong technical understanding of network security requirements'
),

-- Incident Response Policy Acknowledgments
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-IR-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  (SELECT id FROM security_users WHERE username = 'sarah.alnuaimi' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '3.0',
  '2023-09-20T08:00:00Z',
  'training',
  true,
  '2023-09-20T16:00:00Z',
  97.0,
  true,
  'Participated in tabletop exercise and demonstrated excellent response capabilities',
  '2024-01-12T08:00:00Z',
  'Exemplary understanding of incident response procedures'
);

-- Insert sample policy violations
INSERT INTO policy_violations (
  tenant_id,
  policy_id,
  violation_date,
  detected_by,
  detection_method,
  violator_user_id,
  violator_name,
  violator_role,
  violation_type,
  violation_description,
  severity,
  impact_description,
  affected_systems,
  response_actions,
  remediation_plan,
  remediation_status,
  remediation_date,
  investigation_required,
  investigation_notes,
  root_cause,
  disciplinary_action_taken,
  disciplinary_action_description,
  notes
) VALUES
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-AC-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2024-01-08T15:30:00Z',
  'Security Monitoring System',
  'automated',
  (SELECT id FROM security_users WHERE username = 'layla.almheiri' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'Maintenance Technician 2',
  'Maintenance Technician',
  'unauthorized-access-attempt',
  'Attempted to access protection relay configuration without proper authorization',
  'medium',
  'No system impact as access was denied by security controls',
  ARRAY['Protection relay configuration interface'],
  ARRAY['Access denied by system', 'Incident logged', 'Supervisor notified'],
  'Provide additional training on access control procedures and role-based permissions',
  'resolved',
  '2024-01-10T10:00:00Z',
  true,
  'Investigation revealed lack of understanding of proper access request procedures',
  'Insufficient training on access control procedures',
  false,
  null,
  'Resolved through additional training. No malicious intent identified.'
),
(
  (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1),
  (SELECT id FROM security_policies WHERE policy_id = 'POL-TRANS-DP-001' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  '2024-01-12T09:15:00Z',
  'Data Loss Prevention System',
  'automated',
  (SELECT id FROM security_users WHERE username = 'mariam.alkhan' AND tenant_id = (SELECT id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1) LIMIT 1),
  'Operations Analyst 1',
  'Operations Analyst',
  'data-handling-violation',
  'Attempted to email confidential SCADA configuration data to external recipient',
  'high',
  'Potential data exposure prevented by DLP system',
  ARRAY['Email system', 'SCADA configuration database'],
  ARRAY['Email blocked by DLP', 'User notified', 'Security team alerted', 'Manager informed'],
  'Review data handling procedures with user and implement additional controls',
  'in-progress',
  null,
  true,
  'User was preparing report for vendor but used incorrect procedure for data sharing',
  'Lack of awareness of proper data sharing procedures for external parties',
  false,
  null,
  'User cooperation excellent. Implementing enhanced data sharing procedures.'
);