-- Seed data for impact_assessments
-- Requirements: 5.1, 5.2, 8.1

BEGIN;

DO $$
DECLARE
    v_tenant_id UUID;
    v_dubai_site_id UUID;
    v_jebel_site_id UUID;
    v_aweer_site_id UUID;
    v_omar_user_id UUID;
    v_sarah_user_id UUID;
    v_fatima_user_id UUID;
    v_mohammed_user_id UUID;
    v_dubai_node_id UUID;
    v_jebel_node_id UUID;
BEGIN
    -- Get tenant
    SELECT id INTO v_tenant_id FROM tenants WHERE name = 'DEWA - Transmission' LIMIT 1;
    
    IF v_tenant_id IS NULL THEN
        RAISE NOTICE 'Tenant "DEWA - Transmission" not found. Skipping seeding.';
        RETURN;
    END IF;
    
    -- Get sites
    SELECT id INTO v_dubai_site_id FROM sites WHERE name = 'Dubai Main Substation' AND tenant_id = v_tenant_id;
    SELECT id INTO v_jebel_site_id FROM sites WHERE name = 'Jebel Ali Grid Station' AND tenant_id = v_tenant_id;
    SELECT id INTO v_aweer_site_id FROM sites WHERE name = 'Al Aweer Regional Hub' AND tenant_id = v_tenant_id;

    -- Get grid nodes
    SELECT id INTO v_dubai_node_id FROM grid_nodes WHERE name = 'Dubai Main Substation' AND tenant_id = v_tenant_id;
    SELECT id INTO v_jebel_node_id FROM grid_nodes WHERE name = 'Jebel Ali Main Substation' AND tenant_id = v_tenant_id;

    -- Get users
    SELECT id INTO v_omar_user_id FROM security_users WHERE username = 'omar.alfalasi' AND tenant_id = v_tenant_id;
    SELECT id INTO v_sarah_user_id FROM security_users WHERE username = 'sarah.alnuaimi' AND tenant_id = v_tenant_id;
    SELECT id INTO v_fatima_user_id FROM security_users WHERE username = 'fatima.alzahra' AND tenant_id = v_tenant_id;
    SELECT id INTO v_mohammed_user_id FROM security_users WHERE username = 'mohammed.binrashid' AND tenant_id = v_tenant_id;

    -- Clear existing impact assessments for this tenant
    DELETE FROM impact_assessments WHERE tenant_id = v_tenant_id;

    -- Insert Impact Assessments
    INSERT INTO impact_assessments (
        tenant_id, name, description, assessment_type, overall_severity, status,
        assessment_date, assessed_by, customers_affected, mw_at_risk,
        estimated_outage_duration_hours, estimated_recovery_time_hours,
        estimated_cost_usd, revenue_loss_usd, regulatory_fines_usd,
        blast_radius_km, cascade_potential, isolation_possible, backup_paths_available,
        affected_sites, affected_assets, affected_grid_nodes, affected_grid_lines,
        affected_voltage_levels, impact_categories, safety_risk_level,
        public_safety_concern, environmental_impact, confidence_level,
        primary_site_id, primary_grid_node_id
    ) VALUES
    -- Catastrophic Assessments
    (
        v_tenant_id,
        'Protection System Failure - Regional',
        'Assessment of cascading failure potential from protection system compromise',
        'alert',
        'catastrophic',
        'in-progress',
        NOW() - INTERVAL '30 minutes',
        v_omar_user_id,
        2500000,
        3500,
        8,
        24,
        15000000.00,
        25000000.00,
        2000000.00,
        50.0,
        true,
        false,
        false,
        ARRAY[v_jebel_site_id, v_dubai_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV', '33kV'],
        ARRAY['operational', 'financial', 'regulatory', 'safety']::impact_category[],
        5,
        true,
        'Risk of widespread blackout affecting critical infrastructure',
        0.92,
        v_jebel_site_id,
        v_jebel_node_id
    ),
    (
        v_tenant_id,
        'Wide-Area SCADA Compromise Scenario',
        'Worst-case scenario assessment for coordinated SCADA system compromise across all sites',
        'scenario',
        'catastrophic',
        'approved',
        NOW() - INTERVAL '10 days',
        v_mohammed_user_id,
        3200000,
        4500,
        12,
        48,
        25000000.00,
        45000000.00,
        5000000.00,
        75.0,
        true,
        false,
        false,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV', '33kV', '11kV'],
        ARRAY['operational', 'financial', 'regulatory', 'safety', 'reputational']::impact_category[],
        5,
        true,
        'Total loss of remote control and monitoring capabilities',
        0.88,
        v_dubai_site_id,
        v_dubai_node_id
    ),

    -- Major Impact Assessments
    (
        v_tenant_id,
        'SCADA Compromise Impact - Jebel Ali',
        'Assessment of potential impact from SCADA system compromise at Jebel Ali Grid Station',
        'incident',
        'major',
        'completed',
        NOW() - INTERVAL '2 hours',
        v_omar_user_id,
        850000,
        1200,
        4,
        12,
        2500000.00,
        5000000.00,
        500000.00,
        25.0,
        true,
        true,
        true,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'financial', 'regulatory']::impact_category[],
        4,
        true,
        'Potential transformer oil spill risk if cooling systems affected',
        0.85,
        v_jebel_site_id,
        v_jebel_node_id
    ),
    (
        v_tenant_id,
        'Ransomware Attack - Corporate IT',
        'Impact assessment for ransomware spreading to OT networks from corporate systems',
        'scenario',
        'major',
        'approved',
        NOW() - INTERVAL '15 days',
        v_sarah_user_id,
        1200000,
        1800,
        6,
        18,
        8000000.00,
        12000000.00,
        1500000.00,
        35.0,
        true,
        true,
        true,
        ARRAY[v_dubai_site_id, v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'financial', 'reputational']::impact_category[],
        3,
        false,
        'Data backup integrity critical for recovery',
        0.80,
        v_dubai_site_id,
        v_dubai_node_id
    ),
    (
        v_tenant_id,
        'Industroyer Malware Variant',
        'Impact assessment for Industroyer-type malware targeting IEC 61850 infrastructure',
        'scenario',
        'major',
        'approved',
        NOW() - INTERVAL '30 days',
        v_mohammed_user_id,
        1500000,
        2200,
        8,
        20,
        10000000.00,
        18000000.00,
        2000000.00,
        40.0,
        true,
        true,
        true,
        ARRAY[v_jebel_site_id, v_dubai_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'safety', 'regulatory']::impact_category[],
        4,
        true,
        'Protocol-specific malware with deep OT knowledge',
        0.75,
        v_jebel_site_id,
        v_jebel_node_id
    ),
    (
        v_tenant_id,
        'Transmission Line Cascade Failure',
        'Assessment of cyber-induced protection relay misoperation causing cascading line trips',
        'alert',
        'major',
        'in-progress',
        NOW() - INTERVAL '4 hours',
        v_omar_user_id,
        980000,
        1400,
        3,
        10,
        4500000.00,
        7500000.00,
        800000.00,
        30.0,
        true,
        true,
        true,
        ARRAY[v_dubai_site_id, v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV'],
        ARRAY['operational', 'financial', 'safety']::impact_category[],
        4,
        true,
        'Risk of equipment damage from uncontrolled cascade',
        0.87,
        v_dubai_site_id,
        v_dubai_node_id
    ),

    -- Moderate Impact Assessments
    (
        v_tenant_id,
        'Network Intrusion Scenario - Dubai Main',
        'Impact assessment for potential network intrusion at Dubai Main Substation',
        'scenario',
        'moderate',
        'approved',
        NOW() - INTERVAL '1 day',
        v_sarah_user_id,
        450000,
        800,
        2,
        6,
        1200000.00,
        2000000.00,
        200000.00,
        15.0,
        false,
        true,
        true,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV'],
        ARRAY['operational', 'financial']::impact_category[],
        2,
        false,
        NULL,
        0.75,
        v_dubai_site_id,
        v_dubai_node_id
    ),
    (
        v_tenant_id,
        'DDoS Attack on SCADA Gateway',
        'Assessment of service disruption from DDoS attack on SCADA communication infrastructure',
        'incident',
        'moderate',
        'completed',
        NOW() - INTERVAL '7 hours',
        v_fatima_user_id,
        320000,
        600,
        1,
        4,
        800000.00,
        1500000.00,
        100000.00,
        18.0,
        false,
        true,
        true,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['132kV', '33kV'],
        ARRAY['operational', 'financial']::impact_category[],
        1,
        false,
        'Communication redundancy available',
        0.82,
        v_aweer_site_id,
        NULL
    ),
    (
        v_tenant_id,
        'Phishing Campaign Success',
        'Impact if targeted phishing campaign against engineers is successful',
        'scenario',
        'moderate',
        'approved',
        NOW() - INTERVAL '20 days',
        v_sarah_user_id,
        550000,
        900,
        3,
        8,
        1800000.00,
        3000000.00,
        400000.00,
        22.0,
        false,
        true,
        true,
        ARRAY[v_dubai_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'financial', 'reputational']::impact_category[],
        2,
        false,
        'Credential theft leading to lateral movement',
        0.70,
        v_dubai_site_id,
        v_dubai_node_id
    ),
    (
        v_tenant_id,
        'RTU Firmware Vulnerability Exploit',
        'Assessment of impact from mass exploitation of RTU firmware vulnerability',
        'scenario',
        'moderate',
        'approved',
        NOW() - INTERVAL '25 days',
        v_mohammed_user_id,
        670000,
        1000,
        4,
        12,
        3200000.00,
        5500000.00,
        600000.00,
        28.0,
        true,
        true,
        true,
        ARRAY[v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['132kV', '33kV'],
        ARRAY['operational', 'financial', 'regulatory']::impact_category[],
        3,
        false,
        'Multiple RTU vendors affected',
        0.68,
        v_jebel_site_id,
        NULL
    ),
    (
        v_tenant_id,
        'Insider Threat - Engineering Access',
        'Impact assessment for malicious insider with engineering privileges',
        'scenario',
        'major',
        'draft',
        NOW() - INTERVAL '12 days',
        v_omar_user_id,
        780000,
        1100,
        5,
        14,
        4000000.00,
        6500000.00,
        900000.00,
        25.0,
        true,
        true,
        true,
        ARRAY[v_dubai_site_id, v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'financial', 'regulatory', 'safety']::impact_category[],
        4,
        true,
        'Trusted access makes detection difficult',
        0.72,
        v_dubai_site_id,
        v_dubai_node_id
    ),

    -- Minor Impact Assessments
    (
        v_tenant_id,
        'Single HMI Workstation Compromise',
        'Limited impact from compromise of single operator HMI workstation',
        'incident',
        'minor',
        'completed',
        NOW() - INTERVAL '5 days',
        v_fatima_user_id,
        85000,
        150,
        0.5,
        2,
        250000.00,
        400000.00,
        50000.00,
        8.0,
        false,
        true,
        true,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['33kV'],
        ARRAY['operational', 'financial']::impact_category[],
        1,
        false,
        'Backup control available',
        0.90,
        v_aweer_site_id,
        NULL
    ),
    (
        v_tenant_id,
        'Engineering Workstation Malware',
        'Impact of malware infection on isolated engineering workstation',
        'incident',
        'minor',
        'completed',
        NOW() - INTERVAL '8 days',
        v_sarah_user_id,
        0,
        0,
        0,
        1,
        150000.00,
        0.00,
        0.00,
        5.0,
        false,
        true,
        true,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::TEXT[],
        ARRAY['operational']::impact_category[],
        1,
        false,
        'Workstation isolated from operational network',
        0.95,
        v_dubai_site_id,
        NULL
    ),
    (
        v_tenant_id,
        'Failed Patch Deployment',
        'Impact of failed security patch deployment requiring rollback',
        'incident',
        'minor',
        'completed',
        NOW() - INTERVAL '18 days',
        v_mohammed_user_id,
        0,
        0,
        0.25,
        2,
        350000.00,
        200000.00,
        0.00,
        10.0,
        false,
        true,
        true,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['132kV'],
        ARRAY['operational']::impact_category[],
        1,
        false,
        'Patch tested in staging environment first',
        0.88,
        v_jebel_site_id,
        NULL
    ),

    -- Negligible Impact Assessments
    (
        v_tenant_id,
        'Security Awareness Phishing Drill',
        'No-impact assessment for security awareness training exercise',
        'drill',
        'negligible',
        'completed',
        NOW() - INTERVAL '35 days',
        v_sarah_user_id,
        0,
        0,
        0,
        0,
        0.00,
        0.00,
        0.00,
        0.0,
        false,
        true,
        true,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::TEXT[],
        ARRAY[]::impact_category[],
        1,
        false,
        'Controlled training exercise',
        1.0,
        NULL,
        NULL
    ),
    (
        v_tenant_id,
        'Incident Response Tabletop Exercise',
        'Desktop exercise for testing incident response procedures',
        'drill',
        'negligible',
        'completed',
        NOW() - INTERVAL '60 days',
        v_omar_user_id,
        0,
        0,
        0,
        0,
        0.00,
        0.00,
        0.00,
        0.0,
        false,
        true,
        true,
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::TEXT[],
        ARRAY[]::impact_category[],
        1,
        false,
        'Simulated scenario for training',
        1.0,
        NULL,
        NULL
    ),

    -- Additional Scenario Assessments
    (
        v_tenant_id,
        'Supply Chain Attack via Vendor',
        'Assessment of impact from compromised vendor software update',
        'scenario',
        'major',
        'approved',
        NOW() - INTERVAL '45 days',
        v_mohammed_user_id,
        1100000,
        1650,
        6,
        16,
        6500000.00,
        11000000.00,
        1200000.00,
        32.0,
        true,
        true,
        true,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'financial', 'regulatory', 'reputational']::impact_category[],
        3,
        false,
        'Third-party software widely deployed',
        0.65,
        v_dubai_site_id,
        v_dubai_node_id
    ),
    (
        v_tenant_id,
        'Zero-Day IEC 61850 Exploit',
        'Impact of weaponized zero-day vulnerability in IEC 61850 protocol stack',
        'scenario',
        'catastrophic',
        'draft',
        NOW() - INTERVAL '20 days',
        v_sarah_user_id,
        2800000,
        4000,
        10,
        30,
        20000000.00,
        35000000.00,
        3500000.00,
        65.0,
        true,
        false,
        false,
        ARRAY[v_dubai_site_id, v_jebel_site_id, v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV', '33kV'],
        ARRAY['operational', 'financial', 'regulatory', 'safety']::impact_category[],
        5,
        true,
        'No patch available, compensating controls only',
        0.60,
        v_jebel_site_id,
        v_jebel_node_id
    ),
    (
        v_tenant_id,
        'Physical Security Breach + Cyber',
        'Combined physical and cyber attack scenario assessment',
        'scenario',
        'major',
        'approved',
        NOW() - INTERVAL '50 days',
        v_omar_user_id,
        890000,
        1300,
        5,
        14,
        5000000.00,
        8500000.00,
        1000000.00,
        26.0,
        true,
        true,
        true,
        ARRAY[v_aweer_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['132kV', '33kV'],
        ARRAY['operational', 'financial', 'regulatory', 'safety']::impact_category[],
        4,
        true,
        'Physical access enables deeper cyber compromise',
        0.70,
        v_aweer_site_id,
        NULL
    ),
    (
        v_tenant_id,
        'GPS Spoofing - Time Synchronization Attack',
        'Impact assessment for GPS spoofing attack disrupting time synchronization',
        'scenario',
        'moderate',
        'approved',
        NOW() - INTERVAL '40 days',
        v_fatima_user_id,
        420000,
        750,
        2,
        6,
        1600000.00,
        2800000.00,
        350000.00,
        20.0,
        false,
        true,
        true,
        ARRAY[v_jebel_site_id],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY[]::UUID[],
        ARRAY['400kV', '132kV'],
        ARRAY['operational', 'regulatory']::impact_category[],
        2,
        false,
        'Timing critical for protective relaying',
        0.68,
        v_jebel_site_id,
        v_jebel_node_id
    );

END $$;

COMMIT;