-- Completely disable RLS for local development
-- This turns off all Row Level Security restrictions, allowing unrestricted access via anon key
-- WARNING: Do NOT use this in production!

-- Core tables
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sites DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS asset_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tags DISABLE ROW LEVEL SECURITY;

-- Telemetry and operational
ALTER TABLE IF EXISTS telemetry_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS operational_data DISABLE ROW LEVEL SECURITY;

-- Grid topology
ALTER TABLE IF EXISTS grid_nodes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grid_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grid_asset_links DISABLE ROW LEVEL SECURITY;

-- Performance tables
ALTER TABLE IF EXISTS performance_panels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_losses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_bottlenecks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_trends DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_benchmarks DISABLE ROW LEVEL SECURITY;

-- SIM tables
ALTER TABLE IF EXISTS sim_shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_boards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_kpis DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS switching_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS switching_order_impacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outage_impacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_action_links DISABLE ROW LEVEL SECURITY;

-- CI tables
ALTER TABLE IF EXISTS ci_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_project_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_rca DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_countermeasures DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_kpis DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_kpi_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_impacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ci_documents DISABLE ROW LEVEL SECURITY;
