-- Disable RLS for all tables for development
-- This simplifies local development by removing all access restrictions

-- Core tables
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sites DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS asset_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS telemetry_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grid_nodes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grid_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grid_asset_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS operational_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outage_impacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS switching_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS switching_order_impacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tags DISABLE ROW LEVEL SECURITY;

-- Performance tables
ALTER TABLE IF EXISTS performance_benchmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_bottlenecks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_losses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_panels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS performance_trends DISABLE ROW LEVEL SECURITY;

-- Simulation tables
ALTER TABLE IF EXISTS sim_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_action_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_boards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sim_kpis DISABLE ROW LEVEL SECURITY;

-- Transmission topology tables
ALTER TABLE IF EXISTS tx_substations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_bays DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_feeders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_transformers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_lines DISABLE ROW LEVEL SECURITY;

-- Energy meter tables
ALTER TABLE IF EXISTS energy_meters DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_telemetry DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_baselines DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS power_quality_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_power_quality_limits DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS submeters DISABLE ROW LEVEL SECURITY;

-- Analytics tables
ALTER TABLE IF EXISTS energy_kpi_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_benchmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tx_demand_windows DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_anomalies DISABLE ROW LEVEL SECURITY;

-- Grant full access to anon role
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon;

-- Add comment
COMMENT ON DATABASE postgres IS 'RLS disabled for all tables - development mode only. Re-enable for production.';
