apiVersion: v1
kind: Secret
metadata:
  name: plant4.0-secret
type: Opaque
stringData:
  VITE_AZURE_CLIENT_ID: "f996140d-d79b-419d-a64c-f211d23a38ad"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcXlzdHlwamx4cXZna2huYnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTIxMjIsImV4cCI6MjA3NDg4ODEyMn0.F6oqxmEQOIfWpqX9R3syTn6ysHrtzKuZAwA7K8SErtE"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=kfmediaitems;AccountKey=REPLACED_SECRET;EndpointSuffix=core.windows.net"
